CC=gcc
CFLAGS=-pthread -c -g
LDFLAGS=-lncurses
EXECUTABLE=./SoliCurses-C.exe
SRCDIR=./src
BINDIR=./bin

SOURCES=$(wildcard ${SRCDIR}/*.c)

OBJECTS=$(SOURCES:${SRCDIR}/%.c=$(BINDIR)/%.dll)

all : $(EXECUTABLE)

$(EXECUTABLE) : ${OBJECTS}
	$(CC) -o $@ $^ $(LDFLAGS)

$(BINDIR)/%.dll : $(SRCDIR)/%.c
	$(CC) $(CFLAGS) -o $@ $<

clean : 
	rm -rf $(BINDIR)/*.dll $(EXECUTABLE)

run : all
	$(EXECUTABLE)
